Sports/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sports.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

Sports/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sports.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

Sports/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sports.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Sports/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sports.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Sports/Pages/Tests/AddTest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sports.Data;
using Sports.Core;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Sports.Pages.Tests
{
    public class AddTestModel : PageModel
    {
        private readonly ITest ITestData;
        [BindProperty]
        public Test Test { get; set; }

        public IEnumerable<TestListData> TestListData { get; set; }

        [TempData]
        public string message { get; set; }

        public AddTestModel(ITest ITestData)
        {
            this.ITestData = ITestData;
        }
        public IActionResult OnGet()
        {
            Test = new Test();
            TestListData = ITestData.GetAll();
            return Page();

        }
        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                ITestData.Add(Test);
                TempData["Message"] = "Successfully Saved!";
                ITestData.commit();
                return RedirectToPage("./AddTest");
            }
            return Page();

        }
    }
}

Sports/Pages/Tests/EditTestDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sports.Core;
using Sports.Data;

namespace Sports.Pages.Tests
{
    public class EditTestDetailsModel : PageModel
    {
        private readonly ITestDetail TestDetailData;
        [BindProperty]
        public TestDetail testDetail { get; set; }

        public Test Test { get; set; }
        public IEnumerable<AllData> allData { get; set; }
        public IEnumerable<User> users { get; set; }

        public EditTestDetailsModel(ITestDetail testDetailData)
        {
            this.TestDetailData = testDetailData;
        }
        public IActionResult OnGet(int? testDetailId)
        {


            if (testDetailId.HasValue)
            {
                testDetail = TestDetailData.GetTestDetailById(testDetailId.Value);
                users = TestDetailData.GetUsersByTestDetailId(testDetailId.Value);
            }
            return Page();
        }

        public IActionResult OnPostEditAsync(int? testDetailId)
        {
            if (ModelState.IsValid)
            {
                TestDetailData.Update(testDetail);
                TempData["Message"] = "Successfully Saved!";
                TestDetailData.commit();
                return RedirectToPage("./TestDetails",new { testId = testDetail.testId });
            }
            return Page();
        }

        public IActionResult OnPostDeleteAsync(int? testDetailId)
        {
            if (testDetailId.HasValue)
            {
                testDetail = TestDetailData.GetTestDetailById(testDetailId.Value);
                TestDetailData.Delete(testDetailId.Value);
                TempData["Message"] = "Successfully Saved!";
                TestDetailData.commit();
                return RedirectToPage("./TestDetails", new { testId = testDetail.testId });
            }
            return Page();
        }
    }
}

Sports/Pages/Tests/TestDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sports.Core;
using Sports.Data;

namespace Sports.Pages.Tests
{
    public class TestDetailsModel : PageModel
    {
        private readonly ITestDetail TestDetailData;
        [BindProperty]
        public TestDetail TestDetails { get; set; }

        public Test Test { get; set; }
        public IEnumerable<AllData> allData { get; set; }
        public IEnumerable<User> users { get; set; }

        public TestDetailsModel(ITestDetail testDetailData)
        {
            this.TestDetailData = testDetailData;
        }
        public IActionResult OnGet(int? testId)
        {
            TestDetails = new TestDetail();
            
            if(testId.HasValue)
            {
                Test = TestDetailData.GetTest(testId.Value);
                allData = TestDetailData.GetAll(testId.Value);
                users = TestDetailData.GetUsersByTestId(testId.Value);
            }
            return Page();
        }

        public IActionResult OnPostAddAsync(int? testId)
        {
            if (ModelState.IsValid)
            {
                TestDetails.testId = testId.Value;
                TestDetailData.Add(TestDetails);
                TempData["Message"] = "Successfully Saved!";
                TestDetailData.commit();
                return RedirectToPage("./TestDetails");
            }
            return Page();
        }

        public IActionResult OnPostDeleteAsync(int? testId)
        {
            if (testId.HasValue)
            {
                Test = TestDetailData.GetTest(testId.Value);
                TestDetailData.DeleteTestByTestId(testId.Value);
                TempData["Message"] = "Successfully Saved!";
                TestDetailData.commit();
                return RedirectToPage("./AddTest");
            }
            return Page();
        }
    }
}

Sports/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

Sports/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sports/Pages/NotFound.cshtml
@page
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NotFound</title>
</head>
<body>
</body>
</html>

Sports/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sports</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Sports/Pages/Tests/AddTest.cshtml
@page
@model Sports.Pages.Tests.AddTestModel
@{
    ViewData["Title"] = "AddTest";
}
<html>
<body>
    <form method="post">
        <div class="container">
            <div class="text-center">
                <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">CREATE NEW TEST</button>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">CREATE NEW TEST</h4>
                        </div>

                        <div class="modal-body">
                            <div class="form-group">
                                <label for="testType">Type</label>
                                <select class="form-control" asp-for="Test.testType" required>
                                    <option value="Cooper test">Cooper test</option>
                                    <option value="100 Meter sprint">100 Meter sprint</option>
                                </select>
                                <span class="text-danger" asp-validation-for="Test.testType"></span>
                            </div>
                            <div class="form-group">
                                <label for="testDate" class="d-flex justify-content-center">Date</label>
                                <input type="date" class="form-control" asp-for="Test.testDate" required />
                                <span class="text-danger" asp-validation-for="Test.testDate"></span>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="Submit" class="btn btn-default">CREATE TEST</button>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </form>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th class="text-center">Number of Participants</th>
                <th>Test Type</th>
            </tr>
        </thead>
        @foreach (var test in Model.TestListData)
        {

            <tr>
                <td><a asp-page="/Tests/TestDetails" asp-route-testId="@test.testId">@test.testDate</a></td>
                <td class="text-center">@test.count</td>
                <td>@test.testType</td>
            </tr>
        }
    </table>

</body>
</html>

Sports/Pages/Tests/EditTestDetails.cshtml
@page "{testDetailId:int?}"
@model Sports.Pages.Tests.EditTestDetailsModel
@{
    ViewData["Title"] = "EditTestDetails";
}

<form method="post" asp-page-handler="edit">
    <div class="container">
        <div class="text-center"><h2>CHANGE DATA FOR ATHLETE</h2></div>
        <br />
        <input type="hidden" asp-for="testDetail.testId" />
        <input type="hidden" asp-for="testDetail.testDetailId" />
        <div class="form-group">
            <label>Name</label>
            <select class="form-control" asp-for="testDetail.userId">
                <option value="">Choose</option>
                @foreach (var user in Model.users)
                {

                    var isSelected = (user.userId == @Model.testDetail.userId) ? "selected" : "";
                    @if (isSelected == "selected")
                    {
                        <option value="@user.userId" selected="selected">@user.userName</option>
                    }
                    else
                    {
                        <option value="@user.userId">@user.userName</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>Distance(meter)</label>
            <input type="text" asp-for="testDetail.distance" class="form-control" />

        </div>
        <div class="row text-center">
            <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">DELETE ATHLETE FROM TEST</button>
        </div>
        <br />
        <div class="text-center">
            <button type="submit" class="btn btn-default btn-lg">SAVE</button>
        </div>
    </div>
</form>
<form method="post" asp-page-handler="delete">
    <div class="container">

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">CONFIRM</h2>
                    </div>

                    <div class="modal-body">
                        <h3>Do you want to delete this athlete from the test</h3>
                    </div>
                    <div class="modal-footer">
                        <button type="Submit" class="btn btn-default">YES</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">NO</button>
                    </div>
                </div>

            </div>
        </div>

    </div>
</form>

Sports/Pages/Tests/TestDetails.cshtml
@page "{testId:int?}"
@model Sports.Pages.Tests.TestDetailsModel
@{
    ViewData["Title"] = "TestDetails";
}

<a asp-page="/Tests/AddTest"><h2><i class="glyphicon glyphicon-chevron-left"></i></h2></a>
<br />
<div class="row text-center"><h2>@Model.Test.testType  @Model.Test.testDate</h2></div>
<br />
<table class="table">
    <thead>
        <tr>
            <th>Ranking</th>
            <th class="text-center">Distance (meter)</th>
            <th>Fitness Rating</th>
        </tr>
    </thead>
    @foreach (var test in Model.allData)
    {

        <tr>
            <td><a asp-page="/Tests/EditTestDetails" asp-route-testDetailId="@test.testDetailId">@test.userName</a></td>
            <td class="text-center">@test.distance</td>
            <td>
                @if (test.distance <= 1000)
                {
                    <p>Below Average</p>
                }
                else if (test.distance > 1000 && test.distance <= 2000)
                {
                    <p>Average</p>
                }
                else if (test.distance > 2000 && test.distance <= 3500)
                {
                    <p>Good</p>
                }
                else if (test.distance > 3500)
                {
                    <p>Very Good</p>
                }
            </td>
        </tr>
    }
</table>
<div class="text-center">(Click on player to change data)</div>
<br />
<br />
<form method="post" asp-page-handler="add">
    <div class="container">
        <div class="row text-center">
            <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">ADD NEW ATHLETE TO TEST</button>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">ADD NEW ATHLETE TO TEST</h4>
                    </div>

                    <div class="modal-body">
                        <div class="form-group">
                            <label for="testType">Name</label>
                            <select class="form-control" asp-for="TestDetails.userId" required>
                                <option value="">Choose</option>
                                @if (Model.users != null)
                                {
                                    @foreach (var user in Model.users)
                                    {
                                        <option value="@user.userId">@user.userName</option>
                                    }
                                }
                            </select>
                            <span class="text-danger" asp-validation-for="TestDetails.userId"></span>
                        </div>
                        <div class="form-group">
                            <label for="testDate" class="d-flex justify-content-center">Distance</label>
                            <input type="text" class="form-control" asp-for="TestDetails.distance" required />
                            <span class="text-danger" asp-validation-for="TestDetails.distance"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="Submit" class="btn btn-default">Save</button>
                    </div>
                </div>

            </div>
        </div>

    </div>
</form>
<br />
<form method="post" asp-page-handler="delete">
    <div class="text-center"><button type="submit" class="btn btn-default btn-lg">DELETE TEST</button></div>
</form>